CODE elultimojedi.ulx
PICTURE pngPaso res/img/paso.png
PICTURE pngLadera res/img/ladera.png
PICTURE pngAtaqueClones res/img/ataqueclones.png
PICTURE pngAgujero res/img/agujero.png
PICTURE pngLaderaMuerte res/img/laderamuerte.png
PICTURE pngCima res/img/cima.png
PICTURE pngCamino res/img/camino.png
PICTURE pngCueva res/img/cuevavader.png
PICTURE pngPasilloCueva res/img/cuevavader2.png
PICTURE pngExtCadgel res/img/extcadgel.png
PICTURE pngExtCadgelB res/img/extcadgelB.png
PICTURE pngExtCadgelC res/img/extcadgelC.png
PICTURE pngEntradaCadgel res/img/entradacadgel.png
PICTURE pngHangarNorte res/img/hangarnorte.png
PICTURE pngHangarSur res/img/hangarsur.png
PICTURE pngHangarEste res/img/hangareste.png
PICTURE pngHangarOeste res/img/hangaroeste.png
PICTURE pngCuartelMando res/img/cuartelmando.png
PICTURE pngUhumeleAbierta res/img/uhumele_abierta.png
PICTURE pngUhumele res/img/inUhumele.png
PICTURE pngCaza res/img/caza.png
PICTURE pngRampa res/img/rampa.png
PICTURE pngRampaInf res/img/rampainferior.png
PICTURE pngCallejon res/img/callejon.png
PICTURE pngCallejon2 res/img/callejon2.png
PICTURE pngEntradaCeldas res/img/entradaceldas.png
PICTURE pngCeldas res/img/celdas.png
PICTURE pngCalleO4 res/img/calleorvax4.png
PICTURE pngCantina res/img/cantina.png
PICTURE pngPuertoO4 res/img/puertoorvax4.png
PICTURE pngPuenteMandoUhumele res/img/puentemandouhumele.png
PICTURE pngEntradaSotta res/img/entradasotta.png
PICTURE pngEntradaSottaAbierta res/img/entradasottaabierta.png
PICTURE pngEntradaSottaRota res/img/entradasottarota.png
PICTURE pngPasilloSotta res/img/pasilloSotta.png
PICTURE pngAlmacenSotta res/img/almacenSotta.png
PICTURE pngAscensor res/img/ascensor.png
PICTURE pngCeldasSotta res/img/celdasSotta.png
PICTURE pngComedorSotta res/img/comedorsotta.png
PICTURE pngSalaControl res/img/salacontrol.png
PICTURE pngHabSotta res/img/habitacionsotta.png
PICTURE pngHabSottaVacia res/img/habitacionsottavacia.png
PICTURE pngYoda res/img/yoda.png
PICTURE jpgSchurk res/img/schurk.jpg
PICTURE pngBomo res/img/bomo.png
PICTURE pngCrys res/img/crys.png
PICTURE pngKoVakier res/img/kovakier.png
PICTURE pngRaty res/img/raty.png
PICTURE pngSablesLuz res/img/lightsabers.png
SOUND sndIntro res/snd/starwars.ogg
SOUND sndMainTheme res/snd/elultimojedimaintheme.ogg
SOUND sndExplosion res/snd/explosion.ogg
SOUND sndGuerra res/snd/fondoguerra.ogg
SOUND sndCaidaArbol res/snd/caidaarbol.ogg
SOUND sndEnelcaza res/snd/enelcaza.ogg
SOUND sndAlarma res/snd/alarma.ogg
SOUND sndVill res/snd/vill.ogg
SOUND sndTriste res/snd/bomosorrow.ogg
SOUND sndJungla res/snd/ambientejungla.ogg
SOUND sndCueva res/snd/enlacueva.ogg
SOUND sndNave res/snd/spaceshippass.ogg
SOUND sndCantina res/snd/cantina.ogg
SOUND sndPuerto res/snd/puertoorvax.ogg
SOUND sndPlaza res/snd/plazaorvax.ogg
SOUND sndCalleO4 res/snd/calleorvax.ogg
SOUND sndRobot res/snd/robotko.ogg
SOUND sndAbrirPuerta res/snd/abrirpuerta.ogg
SOUND sndRompePuerta res/snd/destrozarpuerta.ogg
SOUND sndAlmacenSotta res/snd/almacensotta.ogg
SOUND sndAlarmaReactor res/snd/alarmareactor.ogg
SOUND sndAbrirCaja res/snd/abrircaja.ogg
SOUND sndRompeCaja res/snd/rompecaja.ogg
SOUND sndBaseSotta res/snd/basesotta.ogg
SOUND sndCampoEnergia res/snd/forcefield.ogg
SOUND sndSalaDescanso res/snd/eastoftunisia.ogg
SOUND sndGranada res/snd/explosiongranada.ogg
PICTURE intro1 res/img/euj1.png
PICTURE intro2 res/img/euj2.png
PICTURE intro3 res/img/euj3.png
PICTURE intro4 res/img/euj4.png
PICTURE intro5 res/img/euj5.png
PICTURE intro6 res/img/euj6.png
PICTURE intro7 res/img/euj7.png
PICTURE intro8 res/img/euj8.png
PICTURE intro9 res/img/euj9.png
PICTURE intro10 res/img/euj10.png
PICTURE intro11 res/img/euj11.png
PICTURE intro12 res/img/euj12.png
PICTURE intro13 res/img/euj13.png
PICTURE intro14 res/img/euj14.png
PICTURE intro15 res/img/euj15.png
PICTURE intro16 res/img/euj16.png
PICTURE intro17 res/img/euj17.png
PICTURE intro18 res/img/euj18.png
PICTURE intro19 res/img/euj19.png
PICTURE intro20 res/img/euj20.png
PICTURE intro21 res/img/euj21.png
PICTURE intro22 res/img/euj22.png
PICTURE intro23 res/img/euj23.png
PICTURE intro24 res/img/euj24.png
PICTURE intro25 res/img/euj25.png
PICTURE intro26 res/img/euj26.png
PICTURE intro27 res/img/euj27.png
PICTURE intro28 res/img/euj28.png
PICTURE intro29 res/img/euj29.png
PICTURE intro30 res/img/euj30.png
PICTURE intro31 res/img/euj31.png
PICTURE intro32 res/img/euj32.png
PICTURE intro33 res/img/euj33.png
PICTURE intro34 res/img/euj34.png
PICTURE intro35 res/img/euj35.png
PICTURE intro36 res/img/euj36.png
PICTURE intro37 res/img/euj37.png
PICTURE intro38 res/img/euj38.png
PICTURE intro39 res/img/euj39.png
PICTURE intro40 res/img/euj40.png
PICTURE intro41 res/img/euj41.png
PICTURE intro42 res/img/euj42.png
PICTURE intro43 res/img/euj43.png
PICTURE intro44 res/img/euj44.png
